// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXKRxyqyeA1HhGiKNIIpxPVTuWQS35b4',
    appId: '1:187072577534:web:3d4d3e41f76fc6ae910aaf',
    messagingSenderId: '187072577534',
    projectId: 'barber-servation',
    authDomain: 'barber-servation.firebaseapp.com',
    storageBucket: 'barber-servation.firebasestorage.app',
    measurementId: 'G-DZ98N2SHQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLsju3QfYgbSB9TvWfRfwqBT3cNMg9LZ4',
    appId: '1:187072577534:android:51d51f6427d8f5d0910aaf',
    messagingSenderId: '187072577534',
    projectId: 'barber-servation',
    storageBucket: 'barber-servation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsOZHjfFpeKp22apUB6CtcLTXuzFJ1bio',
    appId: '1:187072577534:ios:a6f46d662906cef7910aaf',
    messagingSenderId: '187072577534',
    projectId: 'barber-servation',
    storageBucket: 'barber-servation.firebasestorage.app',
    iosBundleId: 'com.example.barberReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsOZHjfFpeKp22apUB6CtcLTXuzFJ1bio',
    appId: '1:187072577534:ios:a6f46d662906cef7910aaf',
    messagingSenderId: '187072577534',
    projectId: 'barber-servation',
    storageBucket: 'barber-servation.firebasestorage.app',
    iosBundleId: 'com.example.barberReservation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXKRxyqyeA1HhGiKNIIpxPVTuWQS35b4',
    appId: '1:187072577534:web:50290974db6f8428910aaf',
    messagingSenderId: '187072577534',
    projectId: 'barber-servation',
    authDomain: 'barber-servation.firebaseapp.com',
    storageBucket: 'barber-servation.firebasestorage.app',
    measurementId: 'G-Z278G9GZ9X',
  );
}
